---
- name: Configure Debian VM
  hosts: webservers
  become: yes
  vars_files:
    - secrets.yml
  vars:
    vimrc_content: |
      call plug#begin()
      Plug 'preservim/NERDTree'
      Plug 'WolfgangMehner/c-support'
      Plug 'WolfgangMehner/bash-support'
      call plug#end()

      syntax on
      set termguicolors
      set tabstop=4
      set softtabstop=4
      set expandtab
      set smartindent
      set shiftwidth=4
      set number
      set numberwidth=4
      set incsearch
      set nohlsearch
      set splitbelow
      set splitright
      set hidden
      set scrolloff=8
      set undofile
      set mouse=a
      set clipboard=unnamedplus
      set ignorecase
      set smartcase

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - sudo
          - vim
          - gh
        state: present

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Remove existing Tailscale
      apt:
        name: tailscale
        state: absent
        purge: yes

    - name: Remove Tailscale state
      file:
        path: /var/lib/tailscale/tailscaled.state
        state: absent

    - name: Install Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      args:
        executable: /bin/bash

    - name: Ensure .vim/autoload directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.vim/autoload"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Install vim-plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/{{ ansible_user }}/.vim/autoload/plug.vim
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        force: true

    - name: Write vimrc content to file
      ansible.builtin.copy:
        content: "{{ vimrc_content }}"
        dest: "/home/{{ ansible_user }}/.vimrc"
        mode: '0644'

    - name: Install vim plugins
      shell: vim +PlugInstall +qall
      args:
        executable: /bin/bash
